#!/bin/bash

function die
{
    echo "$1" >&2
    exit 1
}

target="/boot/recovery.img"
workdir=$(mktemp -d)

cd $workdir
chown root .
chmod 0755 .
cat $target | gunzip | cpio -idmv

mknod -m 600 ./dev/console c 5 1

modpath="/lib/modules/$(uname -r)/"
mkdir -p ./$modpath/kernel/drivers/
rsync -a /$modpath/modules* ./$modpath/
rsync -a /$modpath/vdso ./$modpath/
cp -r /$modpath/kernel/drivers/{char,misc,tty,net} ./$modpath/kernel/drivers/

if [[ $(uname -r) =~ .*gcp ]]
then
    rsync -a /$modpath/kernel/net/ ./$modpath/kernel/net/
fi

rm -rf ./$modpath/kernel/drivers/net/wireless #TODO expand?
cp -r /lib/modules-load.d ./lib/
cp -r /lib/udev ./lib/

rsync -a /etc/{group,passwd,shadow}{,-} ./etc/
sed -i 's@/bin/bash@/bin/sh@g' $img/etc/passwd{,-}
sed -i 's@/opt/delphix/server/bin/supportlogin@/bin/sh@g' $img/etc/passwd{,-}

find . -print0 | cpio --verbose --null --create --format=newc | gzip -7 | tee $target >/dev/null 2>/dev/null

mount -t zfs rpool/grub /mnt
/usr/sbin/grub-mkconfig -o /mnt/boot/grub/grub.cfg
umount /mnt
