Document: recovery-environment
Title: Debian recovery-environment Manual
Author: <insert document author here>
Abstract: This manual describes what recovery-environment is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/recovery-environment/recovery-environment.sgml.gz

Format: postscript
Files: /usr/share/doc/recovery-environment/recovery-environment.ps.gz

Format: text
Files: /usr/share/doc/recovery-environment/recovery-environment.text.gz

Format: HTML
Index: /usr/share/doc/recovery-environment/html/index.html
Files: /usr/share/doc/recovery-environment/html/*.html
