#!/bin/bash
# shellcheck disable=SC2121
# shellcheck disable=SC2154
# shellcheck disable=SC2093

exec tail -n +3 "$0"

if [ x"${bootcount}" = x0 ]; then
	set bootcount=1
elif [ x"${bootcount}" = x1 ]; then
	set bootcount=2
elif [ x"${bootcount}" = x2 ]; then
	set bootcount=3
elif [ x"${bootcount}" = x3 ]; then
	set default="2"
fi
save_env bootcount
