#!/bin/bash

set -euxo pipefail

function die
{
    echo "$1" >&2
    exit 1
}

[[ $# -eq 2 ]] || die "Illegal number of parameters"

ldd $1 2>/dev/null | while read line;
do
    if ! echo "$line" | grep "=>" >/dev/null 2>/dev/null ; then
	echo $line
	continue
    fi
    dep=$(echo "$line" | sed 's/.*=> \(.*\) (.*/\1/')
    dn=$(dirname $dep)
    sudo mkdir -p $2/$dn
    sudo rsync -aL $dep $2/$dep
done
