#!/bin/bash

#
# This script will sync host keys, authorized public keys, and networking
# configuration from the running system to the recovery environment. It should
# be run whenever any of these things change, to ensure that the recovery
# environment remains accessible in the event of a serious system problem.
#

set -euxo pipefail

function cleanup() {
	rm -rf "$workdir"
	rm -f "${target}.tmp"
}

function die() {
	echo "$1" >&2
	exit 1
}

[[ $# -eq 1 ]] || die "Illegal number of parameters"
target="$1"
workdir=$(mktemp -d)
trap cleanup EXIT

cd "$workdir"
chown root .
chmod 0755 .
gunzip <"$target" | cpio -idm

rsync -a /run/systemd/network/ etc/systemd/network
mkdir -p etc/dropbear
#
# Dropbear reads keys in a different format from the normal ssh server. We
# use dropbearconvert to translate them.
#
for fmt in $(find /etc/ssh -name \*key | sed 's/.*host_\(.*\)_key/\1/'); do
	# Unfortunately, dropbear doesn't support ed25519 keys.
	[[ "$fmt" == "ed25519" ]] && continue
	LD_LIBRARY_PATH="./usr/lib/x86_64-linux-gnu" ./usr/lib/dropbear/dropbearconvert \
		openssh dropbear "/etc/ssh/ssh_host_${fmt}_key" \
		"etc/dropbear/dropbear_${fmt}_host_key"
done

rsync -a /etc/machine-id etc/
rsync -a --relative /export/home/delphix/.ssh .

find . -print0 | cpio --null --create --format=newc | gzip -7 >"${target}.tmp"
mv "${target}.tmp" "$target"
