on: [push, pull_request]

jobs:
  check-shfmt:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v1
      - run: sudo ./.github/scripts/install-shfmt.sh
      - run: make shfmtcheck
  check-shellcheck:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v1
      - run: sudo ./.github/scripts/install-shellcheck.sh
      - run: make shellcheck
