on: [push, pull_request]

jobs:
  check-shellcheck:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - uses: delphix/actions/shellcheck@master
  check-shfmt:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - uses: delphix/actions/shfmt@master
